# Generated by Django 5.2.4 on 2025-08-20 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dozhdiepriemnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Основное изображение')),
                ('specifications', models.TextField(blank=True, verbose_name='Общие характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('naruzhnyy_razmer', models.CharField(blank=True, max_length=100, verbose_name='Наружный размер')),
                ('vysota', models.CharField(blank=True, max_length=100, verbose_name='Высота')),
                ('vnutrenniy_diametr', models.CharField(blank=True, max_length=100, verbose_name='Внутренний диаметр')),
                ('glubina_ustanovki_kryshki', models.CharField(blank=True, max_length=100, verbose_name='Глубина установки крышки')),
                ('nominalnaya_nagruzka', models.CharField(blank=True, max_length=100, verbose_name='Номинальная нагрузка')),
                ('ves', models.CharField(blank=True, max_length=100, verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Дождеприемник',
                'verbose_name_plural': 'Дождеприемники',
            },
        ),
        migrations.CreateModel(
            name='Koltsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Основное изображение')),
                ('specifications', models.TextField(blank=True, verbose_name='Общие характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('tip', models.CharField(choices=[('Стеновое', 'Стеновое'), ('Опорное', 'Опорное'), ('Для Колодца', 'Для Колодца')], max_length=50, verbose_name='Тип кольца')),
                ('vnutrenniy_diametr', models.CharField(blank=True, max_length=100, verbose_name='Внутренний диаметр')),
                ('naruzhnyy_diametr', models.CharField(blank=True, max_length=100, verbose_name='Наружный диаметр')),
                ('vysota', models.CharField(blank=True, max_length=100, verbose_name='Высота')),
                ('ves', models.CharField(blank=True, max_length=100, verbose_name='Вес')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Кольцо',
                'verbose_name_plural': 'Кольца',
            },
        ),
        migrations.CreateModel(
            name='KonusnyePerehody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Основное изображение')),
                ('specifications', models.TextField(blank=True, verbose_name='Общие характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('diametr_verhniy', models.CharField(blank=True, max_length=100, verbose_name='Наружный размер')),
                ('diametr_nizhniy', models.CharField(blank=True, max_length=100, verbose_name='Внутренний диаметр')),
                ('vysota', models.CharField(blank=True, max_length=100, verbose_name='Высота')),
                ('tolshchina_stenki', models.CharField(blank=True, max_length=100, verbose_name='Толщина крышки')),
                ('ves', models.CharField(blank=True, max_length=100, verbose_name='Вес')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Номинальная нагрузка')),
            ],
            options={
                'verbose_name': 'Конусный переход',
                'verbose_name_plural': 'Конусные переходы',
            },
        ),
        migrations.CreateModel(
            name='Kryshki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Основное изображение')),
                ('specifications', models.TextField(blank=True, verbose_name='Общие характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('tip', models.CharField(choices=[('Полимерно-песчаный', 'Полимерно-песчаный'), ('Дно колодца', 'Дно колодца')], max_length=50, verbose_name='Тип колодца')),
                ('razmer', models.CharField(blank=True, max_length=100, verbose_name='Наружный диаметр')),
                ('vysota', models.CharField(blank=True, max_length=100, verbose_name='Высота')),
                ('nominalnaya_nagruzka', models.CharField(blank=True, max_length=100, verbose_name='Вес')),
                ('ves', models.CharField(blank=True, max_length=100, verbose_name='Вес')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Колодец',
                'verbose_name_plural': 'Колодца',
            },
        ),
        migrations.CreateModel(
            name='Lyuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Основное изображение')),
                ('specifications', models.TextField(blank=True, verbose_name='Общие характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('naruzhnyy_razmer', models.CharField(blank=True, max_length=100, verbose_name='Наружный размер')),
                ('vysota', models.CharField(blank=True, max_length=100, verbose_name='Высота')),
                ('vnutrenniy_diametr', models.CharField(blank=True, max_length=100, verbose_name='Внутренний диаметр')),
                ('glubina_ustanovki_kryshki', models.CharField(blank=True, max_length=100, verbose_name='Глубина установки крышки')),
                ('nominalnaya_nagruzka', models.CharField(blank=True, max_length=100, verbose_name='Номинальная нагрузка')),
                ('ves', models.CharField(blank=True, max_length=100, verbose_name='Вес')),
                ('tip_vesa', models.CharField(choices=[('Легкий', 'Легкий'), ('Средний', 'Средний'), ('Тяжелый', 'Тяжелый')], max_length=50, verbose_name='Тип по весу')),
            ],
            options={
                'verbose_name': 'Люк',
                'verbose_name_plural': 'Люки',
            },
        ),
        migrations.CreateModel(
            name='VodootvodnyyLotok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Основное изображение')),
                ('specifications', models.TextField(blank=True, verbose_name='Общие характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('naruzhnyy_razmer_lotka', models.CharField(blank=True, max_length=100, verbose_name='Наружный размер лотка')),
                ('vysota', models.CharField(blank=True, max_length=100, verbose_name='Высота')),
                ('nominalnaya_nagruzka', models.CharField(blank=True, max_length=100, verbose_name='Номинальная нагрузка')),
                ('naruzhnyy_razmer_reshetki_lotka', models.CharField(blank=True, max_length=100, verbose_name='Размер решетки')),
                ('ves', models.CharField(blank=True, max_length=100, verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Водоотводный лоток',
                'verbose_name_plural': 'Водоотводные лотки',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True, verbose_name='ID объекта')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='products_pr_content_19215a_idx')],
            },
        ),
    ]
