# Generated by Django 5.2.3 on 2025-07-24 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dozhdiepriemnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('specifications', models.TextField(blank=True, verbose_name='Характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('naruzhnyy_razmer', models.CharField(blank=True, max_length=100, verbose_name='Наружный размер')),
                ('vysota', models.CharField(blank=True, max_length=100, verbose_name='Высота')),
                ('vnutrenniy_diametr', models.CharField(blank=True, max_length=100, verbose_name='Внутренний диаметр')),
                ('glubina_ustanovki_kryshki', models.CharField(blank=True, max_length=100, verbose_name='Глубина установки крышки')),
                ('nominalnaya_nagruzka', models.CharField(blank=True, max_length=100, verbose_name='Номинальная нагрузка')),
                ('ves', models.CharField(blank=True, max_length=100, verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Дождеприемник',
                'verbose_name_plural': 'Дождеприемники',
            },
        ),
        migrations.CreateModel(
            name='Koltsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('specifications', models.TextField(blank=True, verbose_name='Характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tip', models.CharField(choices=[('Стеновое', 'Стеновое'), ('Опорное', 'Опорное'), ('Доборное', 'Доборное')], max_length=50, verbose_name='Тип кольца')),
                ('vnutrenniy_diametr', models.CharField(blank=True, max_length=100, verbose_name='Внутренний диаметр')),
                ('naruzhnyy_diametr', models.CharField(blank=True, max_length=100, verbose_name='Наружный диаметр')),
                ('vysota', models.CharField(blank=True, max_length=100, verbose_name='Высота')),
                ('ves', models.CharField(blank=True, max_length=100, verbose_name='Вес')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Кольцо',
                'verbose_name_plural': 'Кольца',
            },
        ),
        migrations.CreateModel(
            name='KonusnyePerehody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('specifications', models.TextField(blank=True, verbose_name='Характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diametr_verhniy', models.CharField(blank=True, max_length=100, verbose_name='Верхний диаметр')),
                ('diametr_nizhniy', models.CharField(blank=True, max_length=100, verbose_name='Нижний диаметр')),
                ('vysota', models.CharField(blank=True, max_length=100, verbose_name='Высота')),
                ('tolshchina_stenki', models.CharField(blank=True, max_length=100, verbose_name='Толщина стенки')),
                ('ves', models.CharField(blank=True, max_length=100, verbose_name='Вес')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Конусный переход',
                'verbose_name_plural': 'Конусные переходы',
            },
        ),
        migrations.CreateModel(
            name='Kryshki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('specifications', models.TextField(blank=True, verbose_name='Характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tip', models.CharField(choices=[('Круглая', 'Круглая'), ('Квадратная', 'Квадратная'), ('Прямоугольная', 'Прямоугольная')], max_length=50, verbose_name='Тип крышки')),
                ('razmer', models.CharField(blank=True, max_length=100, verbose_name='Размер')),
                ('vysota', models.CharField(blank=True, max_length=100, verbose_name='Высота')),
                ('nominalnaya_nagruzka', models.CharField(blank=True, max_length=100, verbose_name='Номинальная нагрузка')),
                ('ves', models.CharField(blank=True, max_length=100, verbose_name='Вес')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Крышка',
                'verbose_name_plural': 'Крышки',
            },
        ),
        migrations.CreateModel(
            name='Lyuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('specifications', models.TextField(blank=True, verbose_name='Характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('naruzhnyy_razmer', models.CharField(blank=True, max_length=100, verbose_name='Наружный размер')),
                ('vysota', models.CharField(blank=True, max_length=100, verbose_name='Высота')),
                ('vnutrenniy_diametr', models.CharField(blank=True, max_length=100, verbose_name='Внутренний диаметр')),
                ('glubina_ustanovki_kryshki', models.CharField(blank=True, max_length=100, verbose_name='Глубина установки крышки')),
                ('nominalnaya_nagruzka', models.CharField(blank=True, max_length=100, verbose_name='Номинальная нагрузка')),
                ('ves', models.CharField(blank=True, max_length=100, verbose_name='Вес')),
                ('tip_vesa', models.CharField(choices=[('Легкий', 'Легкий'), ('Средний', 'Средний'), ('Тяжелый', 'Тяжелый')], max_length=50, verbose_name='Тип по весу')),
            ],
            options={
                'verbose_name': 'Люк',
                'verbose_name_plural': 'Люки',
            },
        ),
        migrations.CreateModel(
            name='VodootvodnyyLotok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('specifications', models.TextField(blank=True, verbose_name='Характеристики')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('naruzhnyy_razmer_lotka', models.CharField(blank=True, max_length=100, verbose_name='Наружный размер лотка')),
                ('vysota', models.CharField(blank=True, max_length=100, verbose_name='Высота')),
                ('nominalnaya_nagruzka', models.CharField(blank=True, max_length=100, verbose_name='Номинальная нагрузка')),
                ('naruzhnyy_razmer_reshetki_lotka', models.CharField(blank=True, max_length=100, verbose_name='Наружный размер решетки лотка')),
                ('ves', models.CharField(blank=True, max_length=100, verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Водоотводный лоток',
                'verbose_name_plural': 'Водоотводные лотки',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
    ]
