# Generated by Django 5.2.4 on 2025-07-30 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dozhdiepriemnik',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='dozhdiepriemnik',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='dozhdiepriemnik',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='dozhdiepriemnik',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dozhdiepriemnik',
            name='specifications',
            field=models.TextField(blank=True, verbose_name='Общие характеристики'),
        ),
        migrations.AlterField(
            model_name='koltsa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='koltsa',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='koltsa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='koltsa',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='koltsa',
            name='specifications',
            field=models.TextField(blank=True, verbose_name='Общие характеристики'),
        ),
        migrations.AlterField(
            model_name='konusnyeperehody',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='konusnyeperehody',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='konusnyeperehody',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='konusnyeperehody',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='konusnyeperehody',
            name='specifications',
            field=models.TextField(blank=True, verbose_name='Общие характеристики'),
        ),
        migrations.AlterField(
            model_name='kryshki',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='kryshki',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='kryshki',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='kryshki',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='kryshki',
            name='specifications',
            field=models.TextField(blank=True, verbose_name='Общие характеристики'),
        ),
        migrations.AlterField(
            model_name='lyuk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='lyuk',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lyuk',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='lyuk',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lyuk',
            name='specifications',
            field=models.TextField(blank=True, verbose_name='Общие характеристики'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True, verbose_name='ID объекта'),
        ),
        migrations.AlterField(
            model_name='vodootvodnyylotok',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='vodootvodnyylotok',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vodootvodnyylotok',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='vodootvodnyylotok',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vodootvodnyylotok',
            name='naruzhnyy_razmer_reshetki_lotka',
            field=models.CharField(blank=True, max_length=100, verbose_name='Размер решетки'),
        ),
        migrations.AlterField(
            model_name='vodootvodnyylotok',
            name='specifications',
            field=models.TextField(blank=True, verbose_name='Общие характеристики'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['content_type', 'object_id'], name='products_pr_content_19215a_idx'),
        ),
    ]
