# Generated by Django 5.2.4 on 2025-07-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cherepitsa_dozhdiepriemnik_lyuk_trotuarnayaplitka_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(upload_to='hero_images/', verbose_name='Фоновое изображение')),
                ('hero_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('hero_subtitle', models.CharField(max_length=300, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
