# Generated by Django 5.2.4 on 2025-08-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_dozhdiepriemnik_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konusnyeperehody',
            name='diametr_nizhniy',
            field=models.CharField(blank=True, max_length=100, verbose_name='Внутренний диаметр'),
        ),
        migrations.AlterField(
            model_name='konusnyeperehody',
            name='diametr_verhniy',
            field=models.CharField(blank=True, max_length=100, verbose_name='Наружный диаметр'),
        ),
        migrations.AlterField(
            model_name='konusnyeperehody',
            name='material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номинальная нагрузка'),
        ),
        migrations.AlterField(
            model_name='konusnyeperehody',
            name='tolshchina_stenki',
            field=models.CharField(blank=True, max_length=100, verbose_name='Толщина крышки'),
        ),
    ]
